# syntax=docker.io/docker/dockerfile:1.4
ARG _DEV_CONTAINERS_BASE_IMAGE=placeholder
FROM mcr.microsoft.com/devcontainers/go:dev-1.26-bookworm AS dev_container_auto_added_stage_label

ARG TARGETOS
ARG TARGETARCH

ENV KUBECOLORVERSION="0.4.0"
# renovate: datasource=github-releases depName=casey/just
ENV JUSTVERSION="1.58.0"
# renovate: datasource=github-releases depName=kubernetes-sigs/krew
ENV KREWVERSION="0.5.0"

ENV GOEXPERIMENT="jsonv2"

# Install kubecolor
RUN curl -L -o kubecolor.tar.gz https://github.com/kubecolor/kubecolor/releases/download/v${KUBECOLORVERSION}/kubecolor_${KUBECOLORVERSION}_linux_${TARGETARCH}.tar.gz && tar -xvzf kubecolor.tar.gz && install -c -m 0755 kubecolor /usr/local/bin

# Install just
RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --tag ${JUSTVERSION} --to /usr/local/bin

# Install bash-complete to make kubectl autocomplete work
RUN apt-get update && apt-get install bash-completion vim -y && rm -rf /var/lib/apt/lists/*

# Install krew as the user that runs the container, it installs into $HOME/.krew
USER vscode

# Install transmuter
# Needs to run under the vscode user or will kill permissions later
RUN go install github.com/helmetica-framework/transmuter@latest

RUN curl -L -o krew.tar.gz https://github.com/kubernetes-sigs/krew/releases/download/v${KREWVERSION}/krew-linux_${TARGETARCH}.tar.gz && tar -xzf krew.tar.gz && ./krew-linux_${TARGETARCH} install krew && rm -rf krew.tar.gz krew-linux_${TARGETARCH} LICENSE
ENV PATH="/home/vscode/.krew/bin:${PATH}"
USER root

FROM $_DEV_CONTAINERS_BASE_IMAGE AS dev_containers_target_stage

USER root

COPY ./.devsy-internal/ /tmp/build-features/
RUN chmod -R 0755 /tmp/build-features && ls /tmp/build-features

RUN \
echo "_CONTAINER_USER_HOME=$(getent passwd root | cut -d: -f6)" >> /tmp/build-features/devcontainer-features.builtin.env && \
echo "_REMOTE_USER_HOME=$(getent passwd vscode | cut -d: -f6)" >> /tmp/build-features/devcontainer-features.builtin.env

ENV DOCKER_BUILDKIT=1
RUN cd /tmp/build-features/0 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh


RUN cd /tmp/build-features/1 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh

ENV PATH=/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:${PATH}
RUN cd /tmp/build-features/2 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh


RUN cd /tmp/build-features/3 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh


RUN cd /tmp/build-features/4 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh



ARG _DEV_CONTAINERS_IMAGE_USER=root
USER $_DEV_CONTAINERS_IMAGE_USER